name: Django-app workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: | 
        # pip upgrade
        python -m pip install --upgrade pip 
        # flake8 install
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # requirements install
        pip install -r requirements.txt 

    - name: Test with flake8 and django tests
      run: |
        # linter flake8 check
        python -m flake8
        # go to a manage.py folder
        cd infra_project/
        # run tests
        python manage.py test